spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 30000
          writetimeout: 5000

  thymeleaf:
    enable: true

envio:
  email:
  remetente: ste.aoc@gmail.com
  nomeRemetente: 'Stephanie'

server:
  port: 8082
